### ISSUE TITLE
siteConfig.url is configured wrong

### ISSUE THREAD

**Issue by paulbtw** [michidk/MVG-Infoscreen#19]
In the current production version, the homepage returns a branch URL (See the image). 
This makes it a bit annoying to use :(.
![image](https://github.com/michidk/MVG-Infoscreen/assets/25973853/c939c051-c277-4f7b-b0fe-21eb9758a744)

**Comment by michidk** [comment]
Fixed in https://github.com/michidk/MVG-Infoscreen/pull/20
